version: '3.8'

services:
  xmrig:
    image: xmrig-custom
    container_name: xmrig_miner
    restart: always
    volumes:
      - ./xmrig_config/config.json:/xmrig/config.json
    command: -c /xmrig/config.json
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
